#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current: %s]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$current" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=4

API_PROJECT="src/Peoplise.Api"

if [[ ! -f "${API_PROJECT}/Peoplise.Api.csproj" ]]; then
  printf 'Run this from the repo root (PeopliseNewGen/) — %s/Peoplise.Api.csproj not found from %s.\n' "$API_PROJECT" "$(pwd)"
  exit 1
fi

# dotnet isn't on PATH by default in this environment (see the repo's own dev-notes).
if ! command -v dotnet >/dev/null 2>&1 && [[ -x /usr/local/share/dotnet/dotnet ]]; then
  export PATH="$PATH:/usr/local/share/dotnet"
fi
export DOTNET_ROLL_FORWARD=LatestMajor

banner "Mailtrap SMTP sandbox for candidate-link emails"

# ── Stage 1: create/open the Mailtrap sandbox inbox ────────────────────────
stage "Mailtrap: sign up and open your sandbox inbox"
say "This unblocks candidate-link delivery (ConversationsController/CasesController"
say "emailing a candidate their bot-chat/video-interview link). Mailtrap's free"
say "sandbox never sends real email to a real candidate — every message lands in a"
say "private test inbox you can view in the browser, which is exactly what makes"
say "this feature genuinely live-testable without risking a real send."
open_url "https://mailtrap.io/register/signup"
step "Sign up (or sign in) — the free plan is enough for this."
step "Open Email Testing → Inboxes, and click into your default inbox (or create one)."
confirm "You're looking at a sandbox inbox now?" || {
  warn "Come back to this stage once you have an inbox open — the next stage needs its SMTP credentials."
}

# ── Stage 2: copy the SMTP credentials ──────────────────────────────────────
stage "Mailtrap: copy the SMTP credentials"
say "Inside the inbox, open the 'SMTP Settings' tab (integration dropdown may say"
say "'Show Credentials' or similar) — it shows a Host, Port, Username, and Password."
step "Copy each value from that panel into the prompts below."
ask MAILTRAP_HOST "SMTP Host (usually sandbox.smtp.mailtrap.io):"
[[ -z "$MAILTRAP_HOST" ]] && MAILTRAP_HOST="sandbox.smtp.mailtrap.io"
ask MAILTRAP_PORT "SMTP Port (usually 587):"
[[ -z "$MAILTRAP_PORT" ]] && MAILTRAP_PORT="587"
ask MAILTRAP_USERNAME "SMTP Username:"
ask_secret MAILTRAP_PASSWORD "SMTP Password:"

# ── Stage 3: pick a From address ────────────────────────────────────────────
stage "Choose a From address"
say "The sandbox never delivers anywhere real, so any address works — it only"
say "shows up as the sender inside your Mailtrap inbox."
ask MAILTRAP_FROM_ADDRESS "From address (e.g. no-reply@peoplise.dev):"
[[ -z "$MAILTRAP_FROM_ADDRESS" ]] && MAILTRAP_FROM_ADDRESS="no-reply@peoplise.dev"
ask MAILTRAP_FROM_NAME "From name (e.g. Peoplise):"
[[ -z "$MAILTRAP_FROM_NAME" ]] && MAILTRAP_FROM_NAME="Peoplise"

# ── Stage 4: save to this project's local secrets ──────────────────────────
stage "Save it to this project's local secrets"
say "This project keeps local-dev secrets in .NET user-secrets, not in a committed"
say "file — the same place ${API_PROJECT}'s other placeholder settings (AI:Anthropic:ApiKey,"
say "Auth:Certificates) are meant to be filled in, per its own appsettings.json."
if command -v dotnet >/dev/null 2>&1; then
  if [[ -n "$MAILTRAP_HOST" && -n "$MAILTRAP_USERNAME" && -n "$MAILTRAP_PASSWORD" ]]; then
    dotnet user-secrets set "Email:Smtp:Host" "$MAILTRAP_HOST" --project "$API_PROJECT" >/dev/null
    dotnet user-secrets set "Email:Smtp:Port" "$MAILTRAP_PORT" --project "$API_PROJECT" >/dev/null
    dotnet user-secrets set "Email:Smtp:Username" "$MAILTRAP_USERNAME" --project "$API_PROJECT" >/dev/null
    dotnet user-secrets set "Email:Smtp:Password" "$MAILTRAP_PASSWORD" --project "$API_PROJECT" >/dev/null
    dotnet user-secrets set "Email:Smtp:FromAddress" "$MAILTRAP_FROM_ADDRESS" --project "$API_PROJECT" >/dev/null
    dotnet user-secrets set "Email:Smtp:FromName" "$MAILTRAP_FROM_NAME" --project "$API_PROJECT" >/dev/null
    # Mailtrap's sandbox speaks STARTTLS on 587/25/2525, not implicit TLS —
    # SmtpEmailSender's UseSsl toggle picks MailKit's SecureSocketOptions.Auto
    # either way, but false documents intent clearly for this sandbox target.
    dotnet user-secrets set "Email:Smtp:UseSsl" "false" --project "$API_PROJECT" >/dev/null
    printf '  %s✓ set%s Email:Smtp:* in dotnet user-secrets for %s\n' "$GREEN" "$RESET" "$API_PROJECT"
    WRITTEN_SECRET+=("Email:Smtp:Host/Port/Username/Password/FromAddress/FromName/UseSsl (dotnet user-secrets)")
  else
    warn "missing Host/Username/Password from the previous stages; nothing to save. Re-run this wizard once you have them."
    SKIPPED+=("Email:Smtp:* — Host/Username/Password not entered")
  fi
else
  warn "dotnet isn't on PATH — couldn't set the secrets automatically."
  SKIPPED+=("Email:Smtp:* — run manually with dotnet user-secrets set \"Email:Smtp:<Key>\" \"<value>\" --project $API_PROJECT")
fi
note "CandidateApp:BaseUrl (which link the emailed URL points at) is a plain"
note "appsettings.json setting, not a secret, so this wizard doesn't touch it — it"
note "already defaults to http://localhost:5174 for local dev."

finish
